@startuml test
!define Devops https://raw.githubusercontent.com/xNok/devops-plantuml-sprites/main/sprites
!includeurl Devops/docker_logo.puml

actor alice
node "<$devops_docker_logo,color=blue>" as docker

alice -> docker

@endumls