!define DevopsSprites https://raw.githubusercontent.com/xNok/devops-plantuml-sprites/main/sprites
!includeurl DevopsSprites/developer_happy.puml
!includeurl DevopsSprites/developer_evil.puml

!definelong HappyDeveloper(e_alias, e_label)
skinparam rectangleTextAlignment<<HappyDeveloper>> center
skinparam componentTextAlignment<<HappyDeveloper>> center
skinparam componentDefaultTextAlignment<<HappyDeveloper>> center
skinparam componentBorderColor<<HappyDeveloper>> transparent
skinparam backgroundColor<<HappyDeveloper>> transparent
skinparam defaultTextAlignment<<HappyDeveloper>> center
hide <<HappyDeveloper>> stereotype
rectangle "==e_label\n<color:green><$devops_developer_happy></color>\n" <<HappyDeveloper>> as e_alias
!enddefinelong

!definelong EvilDeveloper(e_alias, e_label)
skinparam rectangleTextAlignment<<EvilDeveloper>> center
skinparam componentTextAlignment<<EvilDeveloper>> center
skinparam componentDefaultTextAlignment<<EvilDeveloper>> center
skinparam componentBorderColor<<EvilDeveloper>> transparent
skinparam backgroundColor<<EvilDeveloper>> transparent
skinparam defaultTextAlignment<<EvilDeveloper>> center
hide <<EvilDeveloper>> stereotype
rectangle "==e_label\n<color:red><$devops_developer_evil></color>\n" <<EvilDeveloper>> as e_alias
!enddefinelong